# Generated by Django 4.2.7 on 2024-02-21 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Имя')),
            ],
            options={
                'verbose_name': ('Категорию',),
                'verbose_name_plural': 'Категории',
            },
        ),
    ]
