# Generated by Django 4.2.7 on 2024-02-25 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_categories_slug_product_slug_alter_categories_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='name',
            field=models.TextField(max_length=50, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.TextField(max_length=50, unique=True, verbose_name='Название'),
        ),
    ]
